package(default_visibility = ["//visibility:public"])

py_library(
    name = "models",
    srcs = glob(["*.py"]),
    deps = [
        "//sbcman/hardware:hardware",        
        "//sbcman/services:services",
    ],

)