# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: os_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fos_config.proto\x12\x06sbcman\"6\n\x0cSystemConfig\x12\x17\n\x0fpackage_manager\x18\x01 \x01(\t\x12\r\n\x05shell\x18\x02 \x01(\t\"\x1c\n\x0cOSPathConfig\x12\x0c\n\x04temp\x18\x01 \x01(\t\"f\n\x08OSConfig\x12\x0f\n\x07os_type\x18\x01 \x01(\t\x12$\n\x06system\x18\x02 \x01(\x0b\x32\x14.sbcman.SystemConfig\x12#\n\x05paths\x18\x03 \x01(\x0b\x32\x14.sbcman.OSPathConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'os_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SYSTEMCONFIG']._serialized_start=27
  _globals['_SYSTEMCONFIG']._serialized_end=81
  _globals['_OSPATHCONFIG']._serialized_start=83
  _globals['_OSPATHCONFIG']._serialized_end=111
  _globals['_OSCONFIG']._serialized_start=113
  _globals['_OSCONFIG']._serialized_end=215
# @@protoc_insertion_point(module_scope)
