# Copyright (C) 2025 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

package(default_visibility = ["//visibility:public"])

py_library(
    name = "services",
    srcs = glob(["*.py"]),
    deps = [
        "@sbc_man_pip_deps//pygame_ce",
        "@sbc_man_pip_deps//requests",
    ],
)