package(default_visibility = ["//visibility:public"])

py_library(
    name = "services",
    srcs = [
        "__init__.py",
        "file_ops.py",
        "input_handler.py",
        "network.py",
        "process_launcher.py",
    ],
    deps = [
 #       "//sbcman/models:models",
        "@sbc_man_pip_deps//pygame_ce",
        "@sbc_man_pip_deps//requests",
    ],
)