# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x65vice_config.proto\x12\x06sbcman\"\xaa\x01\n\rDisplayConfig\x12\x33\n\x10resolution_value\x18\x01 \x01(\x0b\x32\x17.sbcman.ResolutionValueH\x00\x12\x19\n\x0f\x61uto_resolution\x18\x02 \x01(\tH\x00\x12\x12\n\nfullscreen\x18\x03 \x01(\x08\x12\x12\n\nfps_target\x18\x04 \x01(\x05\x12\x13\n\x0bhide_cursor\x18\x05 \x01(\x08\x42\x0c\n\nresolution\"0\n\x0fResolutionValue\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"A\n\x0bInputConfig\x12\x18\n\x10joystick_enabled\x18\x01 \x01(\x08\x12\x18\n\x10keyboard_enabled\x18\x02 \x01(\x08\"9\n\nPathConfig\x12\r\n\x05games\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x03 \x01(\t\"A\n\x11PerformanceConfig\x12\r\n\x05vsync\x18\x01 \x01(\x08\x12\x1d\n\x15hardware_acceleration\x18\x02 \x01(\x08\"&\n\x0cUpdateConfig\x12\x16\n\x0erepository_url\x18\x01 \x01(\t\"\xe8\x01\n\x0c\x44\x65viceConfig\x12\x13\n\x0b\x64\x65vice_type\x18\x01 \x01(\t\x12&\n\x07\x64isplay\x18\x02 \x01(\x0b\x32\x15.sbcman.DisplayConfig\x12\"\n\x05input\x18\x03 \x01(\x0b\x32\x13.sbcman.InputConfig\x12!\n\x05paths\x18\x04 \x01(\x0b\x32\x12.sbcman.PathConfig\x12.\n\x0bperformance\x18\x05 \x01(\x0b\x32\x19.sbcman.PerformanceConfig\x12$\n\x06update\x18\x06 \x01(\x0b\x32\x14.sbcman.UpdateConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPLAYCONFIG']._serialized_start=32
  _globals['_DISPLAYCONFIG']._serialized_end=202
  _globals['_RESOLUTIONVALUE']._serialized_start=204
  _globals['_RESOLUTIONVALUE']._serialized_end=252
  _globals['_INPUTCONFIG']._serialized_start=254
  _globals['_INPUTCONFIG']._serialized_end=319
  _globals['_PATHCONFIG']._serialized_start=321
  _globals['_PATHCONFIG']._serialized_end=378
  _globals['_PERFORMANCECONFIG']._serialized_start=380
  _globals['_PERFORMANCECONFIG']._serialized_end=445
  _globals['_UPDATECONFIG']._serialized_start=447
  _globals['_UPDATECONFIG']._serialized_end=485
  _globals['_DEVICECONFIG']._serialized_start=488
  _globals['_DEVICECONFIG']._serialized_end=720
# @@protoc_insertion_point(module_scope)
