# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sbcman/proto/game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sbcman/proto/game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sbcman/proto/game.proto\x12\x0csbcman.proto\"*\n\x0cInputMapping\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"+\n\nResolution\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\xd1\x02\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x14\n\x0cinstall_path\x18\x06 \x01(\t\x12\x13\n\x0b\x65ntry_point\x18\x07 \x01(\t\x12\x11\n\tinstalled\x18\x08 \x01(\x08\x12\x14\n\x0c\x64ownload_url\x18\t \x01(\t\x12\x39\n\x15\x63ustom_input_mappings\x18\n \x03(\x0b\x32\x1a.sbcman.proto.InputMapping\x12\x33\n\x11\x63ustom_resolution\x18\x0b \x01(\x0b\x32\x18.sbcman.proto.Resolution\x12\x12\n\ncustom_fps\x18\x0c \x01(\x05\x12\x13\n\x0bstartScript\x18\r \x01(\t\x12\x0c\n\x04icon\x18\x0e \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sbcman.proto.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTMAPPING']._serialized_start=41
  _globals['_INPUTMAPPING']._serialized_end=83
  _globals['_RESOLUTION']._serialized_start=85
  _globals['_RESOLUTION']._serialized_end=128
  _globals['_GAME']._serialized_start=131
  _globals['_GAME']._serialized_end=468
# @@protoc_insertion_point(module_scope)
