# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input_mappings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14input_mappings.proto\x12\x06sbcman\"\xa9\x01\n\rInputMappings\x12\x0f\n\x07\x63onfirm\x18\x01 \x03(\t\x12\x0e\n\x06\x63\x61ncel\x18\x02 \x03(\t\x12\x0c\n\x04menu\x18\x03 \x03(\t\x12\n\n\x02up\x18\x04 \x03(\t\x12\x0c\n\x04\x64own\x18\x05 \x03(\t\x12\x0c\n\x04left\x18\x06 \x03(\t\x12\r\n\x05right\x18\x07 \x03(\t\x12\x0f\n\x07page_up\x18\x08 \x03(\t\x12\x11\n\tpage_down\x18\t \x03(\t\x12\x0e\n\x06select\x18\n \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'input_mappings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTMAPPINGS._serialized_start=33
  _INPUTMAPPINGS._serialized_end=202
# @@protoc_insertion_point(module_scope)
