package(default_visibility = ["//visibility:public"])

py_library(
    name = "states",
    srcs = glob(["*.py"]),
    deps = [
        "//sbcman/models:models",
        "//sbcman/services:services",
        "@sbc_man_pip_deps//pygame_ce",
    ],
)