package(default_visibility = ["//visibility:public"])

py_library(
    name = "hardware",
    srcs = [
        "__init__.py",
        "compat_sdl.py",
        "config_loader.py",
        "detector.py",
        "prober.py",
    ],
    deps = [],
)