package(default_visibility = ["//visibility:public"])

py_library(
    name = "models",
    srcs = glob(["*.py"]),    
    deps = [
        "//src/hardware:hardware",        
        "//src/services:services",
    ],

)