package(default_visibility = ["//visibility:public"])

py_library(
    name = "models",
    srcs = [
        "__init__.py",
        "config_manager.py",
        "download_manager.py",
        "game.py",
        "game_library.py",
    ],
    deps = [
        "//src/services:services",
    ],

)